homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Discover some devices automatically
# discovery:

# Show links to resources in log and frontend
# introduction:

# Checks for available updates
updater:

# View all events in a logbook
logbook:

recorder:
  purge_days: 21

# Prediction of weather
sensor: !include_dir_merge_list sensor/

switch: !include_dir_merge_list switch/

input_slider: !include_dir_named input_slider/

input_select: !include_dir_named input_select/

automation: !include_dir_merge_list automation/

#media_player:
#  platform: braviatv
#  host: 192.168.0.205
#  name: TV Salon

camera:
  platform: generic
  still_image_url: !secret camera_url
  name: Camera de test
  username: !secret camera_user 
  password: !secret camera_password 


notify:
  name: HTML5
  platform: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

group:
  default_view:
    entities:
      - sun.sun
      - sensor.yr_symbol
      - group.general
      - group.thermostat
      - zone.home
      - device_tracker.nico_n7ot
  general:
    entities:
      - sensor.temperature_exterieure
      - sensor.temperature_interieure
#      - media_player.tv_salon
#      - configurator.tv_salon
  chaudiere:
#    view: yes
    entities:
      - sensor.temperature_retour
      - sensor.temperature_depart
      - sensor.temperature_interieure
      - sensor.heures_de_fonctionement
      - sensor.nombre_de_demarage
      - sensor.temperature_calculee_chaudiere
      - sensor.temperature_calculee_interieur
      - sensor.pression_circuit_chauffage
      - sensor.pompe
      - sensor.puissance_bruleur
      - sensor.vitesse_ventilateur
  thermostat:
    entities:
      - sensor.mode_chauffage
      - input_select.therm_program
      - input_select.therm_mode
      - input_slider.days_away
      - sensor.temperature_cible_jour
      - input_slider.target_temp_day
      - sensor.temperature_cible_nuit
      - input_slider.target_temp_night
      - switch.chaudiere_program_p1
      - switch.chaudiere_program_p2
      - switch.chaudiere_program_p3
      - switch.chaudiere_program_p4
  internet:
    entities:
      - sensor.synchro_freebox_up
      - sensor.synchro_freebox_down
  technique:
    view: yes
    entities:
      - group.chaudiere
      - group.internet
      - updater.updater
  divers:
    view: yes
    entities:
      - camera.camera_de_test


# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

http: !include private/http.yaml

mqtt: !include private/mqtt.yaml

influxdb:
  host: 127.0.0.1
  port: 8086
  database: home_assistant
  username: home-assistant
  password: !secret influxdb_password

