homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 285
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  customize: !include_dir_merge_named customize

# Discover some devices automatically
# discovery:

# Show links to resources in log and frontend
# introduction:

# Checks for available updates
updater:
  include_used_components: true

# View all events in a logbook
logbook:

recorder:
  purge_interval: 5
  purge_keep_days: 70

# Prediction of weather
sensor: !include_dir_merge_list sensor/

switch: !include_dir_merge_list switch/

input_number: !include_dir_named input_number/

input_select: !include_dir_named input_select/

automation: !include_dir_merge_list automation/

script: !include_dir_named script/

binary_sensor:
  - platform: mqtt
    name: "EJP"
    state_topic: "ejp/jourJ"
    payload_on: "EST_EJP"
    payload_off: "NON_EJP"
    device_class: "power"
  - platform: mqtt
    name: "EJP lendemain"
    state_topic: "ejp/jour1filtre"
    payload_on: "EST_EJP"
    payload_off: "NON_EJP"
    device_class: "power"
  - platform: mqtt
    name: "Lave Linge"
    state_topic: "divers/lave-linge"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Porte chambre"
    state_topic: "zwave/node/7/user/Door_Window Sensor"
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    device_class: opening
  - platform: mqtt
    name: "Mouvement chambre"
    state_topic: "zwave/node/7/user/Motion Sensor"
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    device_class: motion


input_boolean:
  notify_home:
    name: A la maison
    initial: off
    icon: mdi:car

media_player:
  platform: braviatv
  host: 192.168.0.205
  name: TV Salon
#  scan_interval: 60

camera:
  platform: generic
  still_image_url: !secret camera_url
  name: Camera de test
  username: !secret camera_user 
  password: !secret camera_password 


notify:
  name: HTML5
  platform: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

group:
  default_view:
    view: yes
    entities:
      - sun.sun
      - sensor.yr_symbol
      - group.general
      - group.thermostat
      - zone.home
      - device_tracker.nico_n7ot
      - binary_sensor.ejp
  general:
    entities:
      - sensor.temperature_exterieure
      - sensor.temperature_interieure
      - binary_sensor.ejp
      - binary_sensor.ejp_lendemain
      - binary_sensor.lave_linge
      - media_player.tv_salon
      - configurator.tv_salon
  chaudiere:
    control: hidden
#    view: yes
    entities:
      - sensor.temperature_retour
      - sensor.temperature_depart
      - sensor.temperature_interieure
      - sensor.heures_de_fonctionement
      - sensor.nombre_de_demarage
      - sensor.temperature_calculee_chaudiere
      - sensor.temperature_calculee_interieur
      - sensor.pression_circuit_chauffage
      - sensor.pompe
      - sensor.puissance_bruleur
      - sensor.vitesse_ventilateur
  thermostat:
    control: hidden
    entities:
      - sensor.mode_chauffage
      - input_select.therm_program
      - input_select.therm_mode
      - input_number.days_away
      - sensor.temperature_cible_jour
      - input_number.target_temp_day
      - sensor.temperature_cible_nuit
      - input_number.target_temp_night
      - switch.chaudiere_program_p1
      - switch.chaudiere_program_p2
      - switch.chaudiere_program_p3
      - switch.chaudiere_program_p4
  internet:
    entities:
      - sensor.synchro_freebox_up
      - sensor.synchro_freebox_down
  temperature3D:
    name: Températures
    entities:
      - sensor.temperature_extrudeur
      - sensor.temperature_garage
  ozwbattery:
    name: Batterie ZWave
    entities:
      - sensor.n7battery_level
      - sensor.n9battery_level
      - sensor.n12battery_level
  technique:
    view: yes
    entities:
      - group.chaudiere
      - group.internet
      - updater.updater
      - group.ozwbattery
  imprimante3D:
    view: yes
    entities:
      - group.temperature3D
  divers:
    view: yes
    entities:
      - camera.camera_de_test
      - input_boolean.notify_home
  guirlande:
    control: hidden
    entities:
      - script.red_light_strip
      - script.stop_light_strip 
  capteurchambre:
    control: hidden
    name: capteurs
    entities:
      - sensor.luminosite_chambre
      - sensor.temperature_chambre
      - binary_sensor.mouvement_chambre
      - binary_sensor.porte_chambre
  chambre:
    view: yes
    entities:
      - group.guirlande
      - group.capteurchambre
  system:
    view: yes
    control: hidden
    entities:
      - group.all_automations
      - group.all_devices



# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

http: !include private/http.yaml

mqtt: !include private/mqtt.yaml

influxdb:
  host: influxdb.grazy.ovh
  port: 443
  ssl: true
  verify_ssl: true
  database: home_assistant
  username: nico 
  password: !secret influxdb_password
  exclude:
    entities:
      - media_player.tv_salon
      - group.all_devices
      - group.all_switches
      - group.default_view
      - group.thermostat
      - group.general
      - group.all_automations
      - automation.recup_night_target
      - automation.recup_day_target
      - input_select.therm_program
      - input_select.therm_mode


google_assistant:
  project_id: home-assistant-push-gzo
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - switch
    - light
    - script
#    - group
    
# microsoft_face:
#   api_key: !secret cognitive_api_key

# image_processing:
#  - scan_interval: 120
#    platform: microsoft_face_identify
#    name: "Test"
#    friendly_name: "Test2"
#    group: prive
#    source:
#     - entity_id: camera.camera_de_test


