homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 285
  # 'metric' for the metric system, 'imperial' for the imperial system
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

  customize: !include_dir_merge_named customize

mobile_app:

# Discover some devices automatically
# discovery:

# Show links to resources in log and frontend
# introduction:

# Checks for available updates
updater:
  include_used_components: true

#mqtt_eventstream:
#  publish_topic: ha_es/master/topic
#  subscribe_topic: ha_es/slaves/#
#  ignore_event:
#    - call_service
#    - state_changed

system_health:

# cloud:

# View all events in a logbook
logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 10

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    

# Prediction of weather


sensor: !include_dir_merge_list sensor/

switch: !include_dir_merge_list switch/

input_number: !include_dir_named input_number/

input_select: !include_dir_named input_select/

automation: !include_dir_merge_list automation/

script: !include_dir_named script/

binary_sensor:
  - platform: mqtt
    name: "EJP"
    state_topic: "ejp/jourJ"
    payload_on: "EST_EJP"
    payload_off: "NON_EJP"
    device_class: "power"
  - platform: mqtt
    name: "EJP lendemain"
    state_topic: "ejp/jour1filtre"
    payload_on: "EST_EJP"
    payload_off: "NON_EJP"
    device_class: "power"
  - platform: mqtt
    name: "Lave Linge"
    state_topic: "divers/lave-linge"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "Porte chambre"
    state_topic: "zwave/node/7/user/Door_Window Sensor"
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    device_class: opening
  - platform: mqtt
    name: "Mouvement chambre"
    state_topic: "zwave/node/7/user/Motion Sensor"
    value_template: '{{value_json.value}}'
    payload_on: true
    payload_off: false
    device_class: motion

light:
  - platform: mqtt
    name: "Imprimante 3D"
    command_topic: "octoprint/light/cmd"
    payload_on: "1"
    payload_off: "0"
    state_topic: "octoprint/light/state"
    brightness_command_topic: "octoprint/light/brightcmd"
    brightness_state_topic: "octoprint/light/bright"
    brightness_scale: 100
    qos: 2

climate:
  - platform: mqtt
    name: "Chauffage central"
    temperature_command_topic: "heating/zone-a/day-target-temperaturei/SET"
    temperature_state_topic: "heating/zone-a/day-target-temperature"
#    temperature_low_state_topic: "heating/zone-a/night-target-temperature"
#    temperature_low_command_topic: "heating/zone-a/night-target-temperature/SET"
    temp_step: 0.5
    current_temperature_topic: "heating/zone-a/temperature"
    mode_state_topic: "heating/zone-a/mode-simple"
    mode_command_topic: "heating/zone-a/mode-simple/SET"
    modes:
      - Automatique
      - Jour
      - Nuit
      - Vacances

input_boolean:
  notify_home:
    name: A la maison
    initial: off
    icon: mdi:car

media_player:
  platform: braviatv
  host: 192.168.0.205
  name: TV Salon

camera:
  platform: generic
  still_image_url: !secret camera_url
  name: Camera de test
  username: !secret camera_user 
  password: !secret camera_password 

config:


notify:
  name: HTML5
  platform: html5
  vapid_pub_key: !secret vapid_pub_key 
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - sun.sun
      - sensor.yr_symbol
      - group.general
      - group.thermostat
      - zone.home
      - device_tracker.nico_n7ot
      - binary_sensor.ejp
  general:
    name: Général
    entities:
      - sensor.temperature_exterieure
      - sensor.temperature_interieure
      - binary_sensor.ejp
      - binary_sensor.ejp_lendemain
      - binary_sensor.lave_linge
      - climate.chauffage_central
      - media_player.tv_salon
  chaudiere:
    control: hidden
    name: Chaudière
    entities:
      - sensor.temperature_retour
      - sensor.temperature_depart
      - sensor.temperature_interieure
      - sensor.heures_de_fonctionement
      - sensor.nombre_de_demarage
      - sensor.temperature_calculee_chaudiere
      - sensor.temperature_calculee_interieur
      - sensor.pression_circuit_chauffage
      - sensor.pompe
      - sensor.puissance_bruleur
      - sensor.vitesse_ventilateur
  thermostat:
    control: hidden
    name: Thermostat
    entities:
      - sensor.mode_chauffage
      - input_select.therm_program
      - input_select.therm_mode
      - input_number.days_away
      - sensor.temperature_cible_jour
      - input_number.target_temp_day
      - sensor.temperature_cible_nuit
      - input_number.target_temp_night
      - switch.chaudiere_program_p1
      - switch.chaudiere_program_p2
      - switch.chaudiere_program_p3
      - switch.chaudiere_program_p4
  internet:
    entities:
      - sensor.synchro_freebox_up
      - sensor.synchro_freebox_down
  temperature3D:
    name: Températures
    entities:
      - sensor.temperature_extrudeur
      - sensor.temperature_garage
  ozwbattery:
    name: Batterie ZWave
    entities:
      - sensor.n7battery_level
      - sensor.n9battery_level
      - sensor.n12battery_level
  technique:
    view: yes
    entities:
      - group.chaudiere
      - group.internet
      - updater.updater
      - group.ozwbattery
  imprimante3D:
    view: yes
    entities:
      - group.temperature3D
      - light.imprimante_3d
  divers:
    view: yes
    entities:
      - camera.camera_de_test
      - input_boolean.notify_home
  guirlande:
    control: hidden
    entities:
      - script.red_light_strip
      - script.stop_light_strip
  capteurchambre:
    control: hidden
    name: capteurs
    entities:
#      - sensor.luminosite_chambre
#      - sensor.temperature_chambre
      - binary_sensor.mouvement_chambre
      - binary_sensor.porte_chambre
  chambre:
    view: yes
    entities:
      - group.guirlande
      - group.capteurchambre

  volkswagendashboard:
    name: Volkswagen
    view: yes
    icon: mdi:car
    entities:
      - group.volkswagenswitches
      - group.volkswagensensors
      - group.volkswagenlocation
  volkswagenswitches:
    name: Volkswagen Switches
    control: hidden
    entities:
      - switch.wvwzzzauzj8905986_charging
      - switch.wvwzzzauzj8905986_climatisation
      - switch.wvwzzzauzj8905986_window_heater
      - lock.wvwzzzauzj8905986_doors_locked
      - lock.wvwzzzauzj8905986_trunk_locked
  volkswagensensors:
    name: Volkswagen Information
    control: hidden
    entities:
      - sensor.wvwzzzauzj8905986_battery_level
      - sensor.wvwzzzauzj8905986_fuel_level
      - sensor.wvwzzzauzj8905986_charging_time_left
      - sensor.wvwzzzauzj8905986_odometer
      - sensor.wvwzzzauzj8905986_electric_range
      - sensor.wvwzzzauzj8905986_combustion_range
      - sensor.wvwzzzauzj8905986_combined_range
      - sensor.wvwzzzauzj8905986_last_connected
      - sensor.wvwzzzauzj8905986_service_inspection
      - sensor.wvwzzzauzj8905986_climatisation_target_temperature
      - binary_sensor.wvwzzzauzj8905986_parking_light
      - binary_sensor.wvwzzzauzj8905986_external_power
      - binary_sensor.wvwzzzauzj8905986_climatisation_without_external_power  
  volkswagenlocation:
    name: Volkswagen Location
    control: hidden
    entities:
      - device_tracker.wvwzzzauzj8905986
  system:
    view: yes
    control: hidden
    entities:
      - group.all_automations
      - group.all_devices



# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
# conversation:

freebox:
  host: !secret freeboxhost 
  port: !secret freeboxport

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.1
    - 127.0.0.1
    - ::1

mqtt: !include private/mqtt.yaml

influxdb:
  host: influxdb.grazy.ovh
  port: 443
  ssl: true
  verify_ssl: true
  database: home_assistant
  username: nico 
  password: !secret influxdb_password
  exclude:
    entities:
      - media_player.tv_salon
      - group.all_devices
      - group.all_switches
      - group.default_view
      - group.thermostat
      - group.general
      - group.all_automations
      - automation.recup_night_target
      - automation.recup_day_target
      - input_select.therm_program
      - input_select.therm_mode

shell_command:
  start_tv: !secret wakeonlantv

google_assistant:
  project_id: home-assistant-push-gzo
  service_account: !include private/google-service.json
  exposed_domains:
    - switch
    - light
    - climate
    - media_player
#    - script
#    - group
#  entity_config:
#    script.red_light_strip:
#      name: guirlande rouge
      # type: light
#    script.bbr_light_strip:
#      name: guirlande bleu
      # type: light
#    script.stop_light_strip:
#      name: guirlande stop


# microsoft_face:
#   api_key: !secret cognitive_api_key

# image_processing:
#  - scan_interval: 120
#    platform: microsoft_face_identify
#    name: "Test"
#    friendly_name: "Test2"
#    group: prive
#    source:
#     - entity_id: camera.camera_de_test


