- platform: mqtt
  state_topic: "heating/outside/temperature"
  name: "Temperature exterieure"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/zone-a/temperature"
  name: "Temperature interieure"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/boiler/temperature"
  name: "Temperature depart"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/boiler/return-temperature"
  name: "Temperature retour"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/boiler/start-count"
  name: "Nombre de demarage"
  unit_of_measurement: "x"

- platform: mqtt
  state_topic: "heating/boiler/hours-count"
  name: "Heures de fonctionement"
  unit_of_measurement: "h"

- platform: mqtt
  state_topic: "heating/boiler/calculated-temperature"
  name: "Temperature calculee chaudiere"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/zone-a/calculated-temperature"
  name: "Temperature calculee interieur"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/zone-a/day-target-temperature"
  name: "Temperature cible jour"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/zone-a/night-target-temperature"
  name: "Temperature cible nuit"
  unit_of_measurement: "°C"

- platform: mqtt
  state_topic: "heating/boiler/pressure"
  name: "Pression circuit chauffage"
  unit_of_measurement: "Bar"

- platform: mqtt
  state_topic: "heating/boiler/power-inst"
  name: "Puissance bruleur"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: "heating/boiler/fan-speed"
  name: "Vitesse ventilateur"
  unit_of_measurement: "rpm"

- platform: mqtt
  state_topic: "heating/zone-a/active-mode"
  name: "Mode Chauffage"
 

- platform: mqtt
  state_topic: "heating/boiler/output-state"
  name: "Pompe"
  value_template: '{{ value_json.zone_A_pump }}'

