- platform: darksky
  api_key: !secret darksky_api_key 
  forecast:
    - 0
    - 1
  language: fr
  monitored_conditions:
    - summary
    - icon
    - temperature
    - precip_probability
  scan_interval: '00:10'
