- alias: "end of wash"
  trigger:
    platform: mqtt
    topic: "divers/lave-linge"
    payload: "OFF"
  action:
    service: notify.html5
    data:
      message: "Fin de lessive"
      title: "Lave linge"

