- alias: "end of wash"
  trigger:
    platform: state
    entity_id: binary_sensor.lave_linge
    from: 'on'
    to: 'off'
  action:
    service: notify.html5
    data:
      message: "Fin de lessive"
      title: "Lave linge"

