- alias: "Recup night target"
  trigger:
    platform: mqtt
    topic: "heating/zone-a/night-target-temperature"
  action:
    service: input_number.set_value
    entity_id: input_number.target_temp_night
    data_template:
      value: "{{ trigger.payload }}"
- alias: "Send night target"
  trigger:
    platform: state
    entity_id: input_number.target_temp_night
  action:
    service: mqtt.publish
    data_template:
      topic: "heating/zone-a/night-target-temperature/SET"
      payload: "{{  states.input_number.target_temp_night.state }}"

