- alias: "Recup mode"
  trigger:
    platform: mqtt
    topic: "heating/zone-a/mode-simple"
  action:
    service: input_select.select_option
    entity_id: input_select.therm_mode
    data_template:
      option: "{{ trigger.payload }}"
- alias: "Send mode"
  trigger:
    platform: state
    entity_id: input_select.therm_mode
  action:
    service: mqtt.publish
    data_template:
      topic: "heating/zone-a/mode-simple/SET"
      payload: "{{  states.input_select.therm_mode.state }}"

